# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueSubmitter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubmittedQueries',
        ),
        migrations.AddField(
            model_name='openissues',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
