# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueSubmitter', '0002_auto_20170629_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedissues',
            name='code',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closedissues',
            name='explanation',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scriptcollection',
            name='explanation',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
